### ISSUE TITLE
NeuralSLAM model review and run

### ISSUE THREAD

**Issue by BobMak** [gauravkuppa/DroneObjectNav#7]

**Comment by BobMak** [comment]
getting an error trying to run eval on pre-trained models:
```/home/vlad/anaconda3/envs/DroneObjectNav/bin/python /home/vlad/Projects/DroneObjectNav/Neural-SLAM/main.py --split val --eval 1 --train_global 0 --train_local 0 --train_slam 0 --load_global pretrained_models/model_best.global --load_local pretrained_models/model_best.local --load_slam pretrained_models/model_best.slam --slam_batch_size 16 --total_num_scenes 1
Traceback (most recent call last):
  File "/home/vlad/Projects/DroneObjectNav/Neural-SLAM/main.py", line 15, in <module>
    from env import make_vec_envs
  File "/home/vlad/Projects/DroneObjectNav/Neural-SLAM/env/__init__.py", line 3, in <module>
    from .habitat import construct_envs
  File "/home/vlad/Projects/DroneObjectNav/Neural-SLAM/env/habitat/__init__.py", line 9, in <module>
    from .exploration_env import Exploration_Env
  File "/home/vlad/Projects/DroneObjectNav/Neural-SLAM/env/habitat/exploration_env.py", line 28, in <module>
    from env.habitat.utils.noisy_actions import CustomActionSpaceConfiguration
  File "/home/vlad/Projects/DroneObjectNav/Neural-SLAM/env/habitat/utils/noisy_actions.py", line 12, in <module>
    from habitat_sim.agent.controls import register_move_fn
ImportError: cannot import name 'register_move_fn' from 'habitat_sim.agent.controls' (/home/vlad/anaconda3/envs/DroneObjectNav/lib/python3.7/site-packages/habitat_sim/agent/controls/__init__.py)
```
likely related to having a wrong version of habitat_sim

**Comment by BobMak** [comment]
Reinstalled neuralSlam and its dependencies outside of the conda env, and things seem to be working now.

running pretrained models on eval with `python main.py --split val --eval 1 --train_global 0 --train_local 0 --train_slam 0 \
--load_global pretrained_models/model_best.global \
--load_local pretrained_models/model_best.local \
--load_slam pretrained_models/model_best.slam `:
![noloss](https://user-images.githubusercontent.com/30277772/108615486-90c67000-73b9-11eb-8462-0caa298c87db.png)

**Comment by Harryoter** [comment]
I also have the same problem, but I still cannot fix it. My env version: habitat-sim=v0.1.5, habitat-api=v0.1.5, python=3.7.11. How did you solve it?

**Comment by BobMak** [comment]
I was using incompatible habitat sim and api versions. Installing commits specified in [NeuralSLAM](https://github.com/devendrachaplot/Neural-SLAM/tree/e833e8f20c5a8d71552a5d22fb78ad6980cfc80c) repo helped.
